ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp

overrides:
  '@fewangsit/wangsvue': link:../../../Users/zainkurnia/Library/pnpm/global/5/node_modules/@fewangsit/wangsvue
